### ISSUE TITLE
Delete compiled files

### ISSUE THREAD

**Issue by legendary-acp** [legendary-acp/Basic_programs#31]
There is lots of compiled files like .exe file, .out file file with no extension. They must be deleted

**Comment by Muskan-Mangal** [comment]
I wanna do it. May I?

**Comment by legendary-acp** [comment]
Ya sure.
I am happy that you wanna help 😃

**Comment by Muskan-Mangal** [comment]
we have to delete .md files too? am i right?

**Comment by legendary-acp** [comment]
No. They are for proper text viewing in Github. You need to delete .exe, .out, file with no extension. etc

**Comment by Muskan-Mangal** [comment]
ohk !

**Comment by Muskan-Mangal** [comment]
![image](https://user-images.githubusercontent.com/33172345/46908382-85d4b880-cf3f-11e8-8b00-5891a243ed06.png)
we have to delte this type of file too?

**Comment by legendary-acp** [comment]
Nice
